### ISSUE TITLE
signature expired and rpc call timeout message level

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#111]
I am looking at moving my logs down to level 2 in an effort to reduce the noise.

Because signature expired and rpc call timeout messages may or may not have an action tied to them would it make more sense to move those to a level 2 (warn level)?

Sine info is more of an un-action oriented alert/message?

**Comment by bookchin** [comment]
Yes, we probably need to do a full sweep of core and improve the log level of several things.

**Comment by littleskunk** [comment]
At work we are using log4j. That is awesome because as user I can configurate different loglevels for different modules. I could configurate loglevel debug for the self reporter and write a seperate logfile. Everything else loglevel warn and a second file.

How about https://www.npmjs.com/package/log4js

**Comment by niahmiah** [comment]
I really like apps that use the debug module for troubleshooting. Some dependancies may already support it (Express, mongoose, etc). I would love to see it adopted in core.

**Comment by computeronix** [comment]
FYI contract no longer open to offers probably shouldn't be an error more of an inform

**Comment by bookchin** [comment]
Closing here. See: https://github.com/Storj/core/issues/264
