### ISSUE TITLE
Raspberry Pi?

### ISSUE THREAD

**Issue by auryn-macmillan** [Storj/storjshare-cli#115]
Any chance of getting a Raspberry Pi version?

(Just following up on this - https://storj.readme.io/v1.0/discuss/575bc4c9b1b4d60e00b57c6d - although I'm not the OP)

**Comment by bookchin** [comment]
Have you tried installing on a Pi? Can you share any issues you had doing so? It *should* install and run without any problems.

**Comment by heunland** [comment]
Some users that try to install on rpi have reported Failed to require LevelDOWN errors on the #hardware channel of the slack. This can usually be fixed by `npm install leveldown`  and `export PATH=/usr/local/bin` to apply the fix from https://github.com/Level/leveldown/issues/221

**Comment by super3** [comment]
@phutchins I believe has successful installed and run Storj Share.

**Comment by super3** [comment]
@auryn-macmillan We are working on this, and already plan to post a guide.

**Comment by eliyastein** [comment]
Hey, I see this issue is closed, but wanted to share my experience / ask for some advice. I managed to get storjshare installed on a pi (which took forever) - and now I'm having trouble running it because everything lags like crazy. Here's some info:

`pi@tingy:~ $ time storjshare --help

  Usage: storjshare [options] [command]


  Commands:

    start [options]       begins farming data using the provided datadir
    setup [options]       launches interactive configuration wizard
    dump-key [options]    prints cleartext private key (suitable for import into gui)
    repair-db [options]   attempt to repair a corrupt db and force compaction
    *                     prints the usage information to the console

  Options:

    -h, --help     output usage information
    -V, --version  output the version number


real    0m30.826s
user    0m29.270s
sys     0m1.180s`

`pi@tingy:~ $ cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0003
Serial          : 000000008e33c6cd`

`pi@tingy:~ $ cat /proc/version
Linux version 4.4.13+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #894 Mon Jun 13 12:43:26 BST 2016`

`pi@tingy:~ $ cat /proc/meminfo
MemTotal:         185468 kB
MemFree:           83268 kB
MemAvailable:     134184 kB
Buffers:           13720 kB
Cached:            59000 kB
SwapCached:            0 kB
Active:            57712 kB
Inactive:          22764 kB
Active(anon):       7876 kB
Inactive(anon):     4376 kB
Active(file):      49836 kB
Inactive(file):    18388 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        102396 kB
SwapFree:         102396 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:          7768 kB
Mapped:            13584 kB
Shmem:              4500 kB
Slab:              11840 kB
SReclaimable:       6340 kB
SUnreclaim:         5500 kB
KernelStack:         680 kB
PageTables:          540 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      195128 kB
Committed_AS:      46232 kB
VmallocTotal:     835584 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
CmaTotal:           8192 kB
CmaFree:            3736 kB`

**Comment by rriemann** [comment]
@super3 I guess when you closed the issue back in July, there should be now somewhere a guide. Would you please share the link here? :)

**Comment by super3** [comment]
@rriemann You would have to ask in our community chat. storjshare-cli is deprecated in favor of storjshare-daemon. I'm not sure if someone has run that on a RPI yet. I might give it a try if I get some time.

**Comment by ekaitz-zarraga** [comment]
@super3 @rriemann  I run **storjshare-daemon** on a [A20-Olinuxino-LIME-2](https://www.olimex.com/wiki/A20-OLinuXino-LIME2), it's very similar to a Raspberry Pi. It works perfect.

**Comment by super3** [comment]
@ekaitz-zarraga Great to hear!

**Comment by phutchins** [comment]
I've run storjshare-cli on a pi for 6+ months now with no issue. It does take quite some time to install/update but it runs quite nicely... 

We shouldn't really need a guide as it is installed and run the same way you would on a normal os with nodejs.

**Comment by rriemann** [comment]
Thank you @phutchins for sharing your experience. Could you tell us which kind of storage you use and some metrics on your reward? ;) I would use my media player RPi and wonder if it is bad to deconnect once a week for few hours to watch a movie.

**Comment by phutchins** [comment]
@rriemann, of course! My storage is a simple WD Passport Ultra 1TB external SSD. I don't run the farmer for profit so I honestly haven't paid attention to the return and don't have much to share there. I run then engineering and infrastructure operations at Storj so I always like to have an up to date farmer running with its logs in front of me and the Pi is perfect for that. 

Ideally, a farmer would be online 100% of the time but we realize that's not always possible due to the nature of the internet and connectivity. After our audit service is live, if your farmer were to go down during the time of a few audits, it's possible that the contract would be given to a different farmer which is not desireable. We do realize that there are plenty of implementations like this where a farmer would expect downtime so we're working on incorporating that into our model...
