### ISSUE TITLE
Throttle Bandwidth Ability

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#128]
Add the ability to throttle bandwidth connections.  Meaning add a couple of features here

1. Add ability to configure max up / down bandwidth so that way the program will only use up to xxx speed when working to prevent over saturation

2. Add automated ability by default to analyze the internet connection (telemetry does this already) and then have a default cap of xx% of total up / down to prevent over-saturation

**Comment by 1credit** [comment]
I would agree.  Noticed the Storj node on my VM had failed and restarted it.  For a few seconds, the network transmission rate approached 11mbit/s on my 7mbit/s connection (obviously my ISP allows for some bursting).  While that burst occurred, flood pings from my LAN to the modems external IP had 100% packet loss.  Situation cleared itself quickly, but for a second or so the modem was overloaded.

Alas it all happened and cleared before I thought about grabbing a screen shot.

**Comment by 1credit** [comment]
Just a note that restarting the new v1.0.0 gui will also cause this problem

**Comment by super3** [comment]
There are 3rd party programs and system configurations you can use to limit Storj Share's bandwidth usage. While this is a feature we would like in the future, to focus on it now would be premature. You can bring it back up again in 2-3 months.

**Comment by 1credit** [comment]
Please provide a few recommendations that allow for per-process limits.  A quick google search showed many ways to throttle at the interface level, but since Storj does not run on dedicated systems, this is unacceptable.   Creating a web-proxy based system seems to be asking a fair amount, and would further complicate the network configuration by intervening in the DNAT process.

Please keep in mind this request was created because without throttle, Storj is capable of disrupting a clients entire network via overloading modem/routers and causing massive packet loss.  Please see issue #122 for more details on that, or join the MatterMost DDOS discussion group.
