### ISSUE TITLE
uses more storage than configured size limit

### ISSUE THREAD

**Issue by davidak** [Storj/storjshare-cli#131]
### Package Versions

```
StorjShare: 5.0.0
Core:       2.0.3
Protocol:   0.7.1
```

node

```
v4.4.5
```

### Expected Behavior

storjshare-cli only use the storage i configured.

### Actual Behavior

storjshare-cli uses alway a 107,4 % of configured size.

| configured | actual use |
|------------|------------|
| 35 GB      | 37,62 GB   |
| 50 GB      | 53,71 GB   |
| 60 GB      | 64,46 GB   |

### Steps to Reproduce

1. configure storage limit
2. wait for some data
3. see actual size of directory

maybe technically not related to https://github.com/Storj/storjshare-cli/issues/63 because there is a limit now, but it's the same topic.

**Comment by bookchin** [comment]
This is a result of two things:

1. We measure in 1024 units (because its the right unit! :P)
2. We use leveldb's `approximateSize` because it performs better then stat'ing every file in the db recursively and that result doesn't always include recently written data

So it's a featurebug. Maybe we can implement something that sets the actual limit to less than what the user supplies, but it still won't be perfect.

**Comment by super3** [comment]
This is a duplicate issue for #92
