### ISSUE TITLE
Can't upload a file on one PC then download on another.

### ISSUE THREAD

**Issue by NutterzUK** [Storj/storjshare-cli#133]
### Package Versions

Replace the values below using the output from `storjshare --version`.

C:\Users\steve>storjshare --version
StorjShare: 5.0.0
Core:       2.0.5
Protocol:   0.7.1

Replace the values below using the output from `node --version`.

C:\Users\steve>node --version
v4.4.5

### Expected Behavior

If a key is not available, prompt for it. Or the CLI should have a way to import keys.

### Actual Behavior

C:\Users\steve>storj download-file 57932e1488fc0f4839e44a49 5793b989a0494c4b27d4842a C:/cat2.jpg
[...]  > Enter your passphrase to unlock your keyring  >  ********

[Sat Jul 23 2016 19:55:17 GMT+0100 (GMT Summer Time)] [info]   Creating retrieval token...
[Sat Jul 23 2016 19:55:18 GMT+0100 (GMT Summer Time)] [info]   Resolving file pointer...
[Sat Jul 23 2016 19:55:19 GMT+0100 (GMT Summer Time)] [info]   Downloading file from 0 channels.
[Sat Jul 23 2016 19:55:19 GMT+0100 (GMT Summer Time)] [error]  No decryption key found in key ring!
events.js:141
     throw er; // Unhandled 'error' event
     ^

### Steps to Reproduce

1) Upload some files using a client other than the Storj CLI, or using the CLI on a different machine..
2) Login on the storj cli using "storj login"
3) Try to download an existing file.

**Comment by super3** [comment]
This is a bit of a grey area. Generally we don't want to hold or be responsible for users decryption keys for their data. Then the issue becomes how can they securely share keys between devices and authorized parties. Do we help them do that securely or is this something that they have to do themselves?

**Comment by NutterzUK** [comment]
Interesting.

One thing I would (personally) massively disagree with would be the encryption keys going anywhere near the bridge, as the bridge knows about the farmers and could potentially put the file back together.

My preference would be just give the end user control over their own keys. Currently with no (user friendly) way to export/import them, using Storj for backups isn't possible as I know if my machine goes down i'm done for (In which case, why am I using Storj?)

For the Java client which I am making I intend to let the user define the encryption key themselves. This just means that they can upload/download with this client on any machine, but if they want to input their encryption key on a CLI client, they can't.

**Comment by super3** [comment]
The more I think about it the more I think we should provide an external tool to help manage keys. You would use this tool/library along with bridge. You would add other devices public key to your local device. When you update your keyring, and you could update the keyring for the other devices encrypted with their public key. That encrypted ciphertext could be reasonable uploaded as a normal file to the network. Bridge would have no knowledge that it was not just not a regular file, and no one would be able to decrypt it except the end the device. Managing those public keys is an issue, but I think a reasonable solution can be found. 

We are not in the business of key management. That being said, we should at least help provide a tool or two to help.

I just realized that this issue is in the wrong repo. The upload and download tools you are referring to live here: https://github.com/storj/core. Please reopen the issue there.
