### ISSUE TITLE
502 Gateway Error Node Crash

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-cli#175]
### Package Versions

```
Windows Machine

StorjShare: 7.0.0-beta
Core:       4.0.0-rc.2
Protocol:   0.8.1

```

```
v4.5.0
```

### Expected Behavior

Node to safely recover and not crash

### Actual Behavior

```
Node crashes with below log

 [error]  Failed to discover seeds from bridge: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run the pre-release storjshare-cli
2. Let it run for a few hours and eventually the log will capture this

 [error]  Failed to discover seeds from bridge: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

**Comment by super3** [comment]
@computeronix This is actually a ongoing Bridge issue.

**Comment by bookchin** [comment]
While it's not good that this was happening, it *is* the expected behavior. This is not a crash - it's an intentional exit.

If there are no seeds in the config, and the node can't access a bridge to discover any, then we exit because there is nothing to do. If you want storjshare to restart automatically when or if this happens, use a process manager like PM2 as described in the README.
