### ISSUE TITLE
Negative free on telemetry reports

### ISSUE THREAD

**Issue by subwolf** [Storj/storjshare-cli#239]
Storjshare V9.0.1
Core V6.0.10
Protocol V1.0.0

Telemetry reports are going out with negative numbers. I put 20 TiB as my NAS is good for that and more, slow as it is. One might expect a rollover to a negative number, but not on a 64-bit OS? When I divide the free count into Gigabytes, I get 465.83. When I divide up the used count, it comes to 1.489TiB which is about right.

```
{"type":"info","message":"telemetry report {\"storage\":{\"free\":-500180626725,\"used\":1599692254501},\"contact\":{\"userAgent\":\"6.0.10\",\"protocol\":\"1.0.0\",\"address\":\"subwolf.dyndns.org\",\"port\":4000,\"nodeID\":\"d23f0dbfb8c2e6abc22b8598e15359b1
3a8e86bf\",\"lastSeen\":1481972358205},\"payment\":\"14ADc8cmKV7Cx6Xo5oRTPDKG57bwVPswuE\"}","timestamp":"2016-12-18T00:20:31.834Z"}
```

**Comment by super3** [comment]
@subwolf Storjshare-CLI is deprecated, and moved to Storjshare-Daemon. Negative free space isn't really too much of an issue. If you get a bunch of contracts at the same time near the edge of your limit, then you will most likely go over by a bit. 

In your listed log, when I covered, I got 500 GB! That is def not supposed to happen. I think this may have been fixed in core a couple days ago. https://github.com/Storj/core/pull/611

Can you verify this happens with a new node? If it does, please open a new issue in daemon.
