### ISSUE TITLE
storjshare should exit when trying to start with a non-existent data directory

### ISSUE THREAD

**Issue by lunokhod** [Storj/storjshare-cli#55]
When starting storjshare with a non-existent data directory, the client enters the setup wizard mode. The ideal behavior would be to print an error that the directory doesn't exist and exit gracefully.

Farmer: v3.0.2
Core:   v0.6.13

**Comment by gordonwritescode** [comment]
I'm not sure that I agree. If the directory does not exist, the wizard starts so that it can be created with the appropriate configuration, keys, and database setup. This is how the first run works for creating the default data directory (`~/.storjshare`). Perhaps adding an additional message to the wizard that states that the directory does not exist and it will be created would be sufficient.

**Comment by lunokhod** [comment]
I should have specified that I encountered this problem during a power outage. In short, after the power came on, the attached drive was not mounted before storjshare restarted. As the data directory did not exist at that point in time, storjshare entered the startup wizard procedure. I think that this is non-ideal behavior.

**Comment by gordonwritescode** [comment]
Ahhh... I see. So the datadir was something like `/mnt/mydrive`? I'm not sure how to get around that. The CLI would have no way of knowing if a drive is supposed to be mounted at a given location. All it knows is what the file system shows. I tend to think that handling this is out of scope and userland should make sure to start things in proper order.

How would you expect the CLI to behave when creating a datadir/configuration for the first time? User needs to manually create the directory? How about the default directory (`~/.storjshare`)? Create it automatically, but require an existing directory in other cases?
