### ISSUE TITLE
Reload config without restarting node

### ISSUE THREAD

**Issue by smilesvua** [Storj/storjshare-cli#93]
### Package Versions

Replace the values below using the output from `storjshare --version`.

```
Farmer: v2.2.4
Core:   v0.6.5
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Storjshare-cli can execute with the new config without restarting and rechecking shards.

### Actual Behavior
Storjshare-cli ignores changes in the config. The new works only after restart node which lead to several hours of checking shards.

```

```

### Steps to Reproduce

1. Change config.
2. Restart the node.
3. Wait for recheck of all shards.

**Comment by bookchin** [comment]
This isn't really feasible, since reloading the config would mean closing all opened ports and reopening them, reconnecting to the network, and rebuilding the routing table. Ultimately changes in the config would need to force the program to act as if it had been restarted.

Seems to me that the real issue here is that the shard reaper does two things that are undesirable:

1. It runs on startup, then again every `CLEAN_INTERVAL`
2. It runs in the same process as the network node

Issue 1 can be resolved by just simply not running the reaper on startup, just waiting until the first `CLEAN_INTERVAL`. Issue 2 is blocked by LevelDB's `LOCK` (a LevelDB can only be accessed by a single process at a time).

I will close this by solving issue 1, which this report seems to indicate as the primary undesirable aspect of restarting your node. The second issue will hopefully become obsolete when the move to LMDB (https://github.com/Storj/core/issues/143).
